### ISSUE TITLE
Refactor alert number field

### ISSUE THREAD

**Issue by whdalsrnt** [cloudforet-io/monitoring#9]
1. Change Type
**integer** -> **string**

2. Change uniquely by domain

**Comment by stat-kwon** [comment]
Currently, in the case of SequenceField of MongoDB, the number increases but the value bounces, so it will be implemented as an Increment of Int field.
* alert_number : `SequenceField` -> `IntField`
* alert_number_str: `StringField`

**Comment by stat-kwon** [comment]
This is related PR information.

[monitoring]
https://github.com/cloudforet-io/monitoring/pull/23

[api]
https://github.com/cloudforet-io/api/pull/24
